# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.31

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/danielhougaard/Documents/git/infisical-cpp-sdk

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/danielhougaard/Documents/git/infisical-cpp-sdk

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/opt/homebrew/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/opt/homebrew/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/opt/homebrew/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/opt/homebrew/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/opt/homebrew/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/opt/homebrew/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/danielhougaard/Documents/git/infisical-cpp-sdk/CMakeFiles /Users/danielhougaard/Documents/git/infisical-cpp-sdk//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/danielhougaard/Documents/git/infisical-cpp-sdk/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named infisical

# Build rule for target.
infisical: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 infisical
.PHONY : infisical

# fast build rule for target.
infisical/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/infisical.dir/build.make CMakeFiles/infisical.dir/build
.PHONY : infisical/fast

#=============================================================================
# Target rules for targets named example

# Build rule for target.
example: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 example
.PHONY : example

# fast build rule for target.
example/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/example.dir/build.make CMakeFiles/example.dir/build
.PHONY : example/fast

#=============================================================================
# Target rules for targets named zlib

# Build rule for target.
zlib: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 zlib
.PHONY : zlib

# fast build rule for target.
zlib/fast:
	$(MAKE) $(MAKESILENT) -f _deps/zlib-build/CMakeFiles/zlib.dir/build.make _deps/zlib-build/CMakeFiles/zlib.dir/build
.PHONY : zlib/fast

#=============================================================================
# Target rules for targets named curl_uninstall

# Build rule for target.
curl_uninstall: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 curl_uninstall
.PHONY : curl_uninstall

# fast build rule for target.
curl_uninstall/fast:
	$(MAKE) $(MAKESILENT) -f _deps/curl-build/CMakeFiles/curl_uninstall.dir/build.make _deps/curl-build/CMakeFiles/curl_uninstall.dir/build
.PHONY : curl_uninstall/fast

#=============================================================================
# Target rules for targets named curl-generate-curl-config.1

# Build rule for target.
curl-generate-curl-config.1: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 curl-generate-curl-config.1
.PHONY : curl-generate-curl-config.1

# fast build rule for target.
curl-generate-curl-config.1/fast:
	$(MAKE) $(MAKESILENT) -f _deps/curl-build/docs/CMakeFiles/curl-generate-curl-config.1.dir/build.make _deps/curl-build/docs/CMakeFiles/curl-generate-curl-config.1.dir/build
.PHONY : curl-generate-curl-config.1/fast

#=============================================================================
# Target rules for targets named curl-generate-mk-ca-bundle.1

# Build rule for target.
curl-generate-mk-ca-bundle.1: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 curl-generate-mk-ca-bundle.1
.PHONY : curl-generate-mk-ca-bundle.1

# fast build rule for target.
curl-generate-mk-ca-bundle.1/fast:
	$(MAKE) $(MAKESILENT) -f _deps/curl-build/docs/CMakeFiles/curl-generate-mk-ca-bundle.1.dir/build.make _deps/curl-build/docs/CMakeFiles/curl-generate-mk-ca-bundle.1.dir/build
.PHONY : curl-generate-mk-ca-bundle.1/fast

#=============================================================================
# Target rules for targets named curl-man

# Build rule for target.
curl-man: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 curl-man
.PHONY : curl-man

# fast build rule for target.
curl-man/fast:
	$(MAKE) $(MAKESILENT) -f _deps/curl-build/docs/libcurl/CMakeFiles/curl-man.dir/build.make _deps/curl-build/docs/libcurl/CMakeFiles/curl-man.dir/build
.PHONY : curl-man/fast

#=============================================================================
# Target rules for targets named curl-opts-man

# Build rule for target.
curl-opts-man: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 curl-opts-man
.PHONY : curl-opts-man

# fast build rule for target.
curl-opts-man/fast:
	$(MAKE) $(MAKESILENT) -f _deps/curl-build/docs/libcurl/opts/CMakeFiles/curl-opts-man.dir/build.make _deps/curl-build/docs/libcurl/opts/CMakeFiles/curl-opts-man.dir/build
.PHONY : curl-opts-man/fast

#=============================================================================
# Target rules for targets named libcurl_shared

# Build rule for target.
libcurl_shared: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 libcurl_shared
.PHONY : libcurl_shared

# fast build rule for target.
libcurl_shared/fast:
	$(MAKE) $(MAKESILENT) -f _deps/curl-build/lib/CMakeFiles/libcurl_shared.dir/build.make _deps/curl-build/lib/CMakeFiles/libcurl_shared.dir/build
.PHONY : libcurl_shared/fast

#=============================================================================
# Target rules for targets named cpr

# Build rule for target.
cpr: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 cpr
.PHONY : cpr

# fast build rule for target.
cpr/fast:
	$(MAKE) $(MAKESILENT) -f _deps/cpr-build/cpr/CMakeFiles/cpr.dir/build.make _deps/cpr-build/cpr/CMakeFiles/cpr.dir/build
.PHONY : cpr/fast

examples/example.o: examples/example.cpp.o
.PHONY : examples/example.o

# target to build an object file
examples/example.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/example.dir/build.make CMakeFiles/example.dir/examples/example.cpp.o
.PHONY : examples/example.cpp.o

examples/example.i: examples/example.cpp.i
.PHONY : examples/example.i

# target to preprocess a source file
examples/example.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/example.dir/build.make CMakeFiles/example.dir/examples/example.cpp.i
.PHONY : examples/example.cpp.i

examples/example.s: examples/example.cpp.s
.PHONY : examples/example.s

# target to generate assembly for a file
examples/example.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/example.dir/build.make CMakeFiles/example.dir/examples/example.cpp.s
.PHONY : examples/example.cpp.s

src/InfisicalClient.o: src/InfisicalClient.cpp.o
.PHONY : src/InfisicalClient.o

# target to build an object file
src/InfisicalClient.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/infisical.dir/build.make CMakeFiles/infisical.dir/src/InfisicalClient.cpp.o
.PHONY : src/InfisicalClient.cpp.o

src/InfisicalClient.i: src/InfisicalClient.cpp.i
.PHONY : src/InfisicalClient.i

# target to preprocess a source file
src/InfisicalClient.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/infisical.dir/build.make CMakeFiles/infisical.dir/src/InfisicalClient.cpp.i
.PHONY : src/InfisicalClient.cpp.i

src/InfisicalClient.s: src/InfisicalClient.cpp.s
.PHONY : src/InfisicalClient.s

# target to generate assembly for a file
src/InfisicalClient.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/infisical.dir/build.make CMakeFiles/infisical.dir/src/InfisicalClient.cpp.s
.PHONY : src/InfisicalClient.cpp.s

src/auth/Auth.o: src/auth/Auth.cpp.o
.PHONY : src/auth/Auth.o

# target to build an object file
src/auth/Auth.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/infisical.dir/build.make CMakeFiles/infisical.dir/src/auth/Auth.cpp.o
.PHONY : src/auth/Auth.cpp.o

src/auth/Auth.i: src/auth/Auth.cpp.i
.PHONY : src/auth/Auth.i

# target to preprocess a source file
src/auth/Auth.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/infisical.dir/build.make CMakeFiles/infisical.dir/src/auth/Auth.cpp.i
.PHONY : src/auth/Auth.cpp.i

src/auth/Auth.s: src/auth/Auth.cpp.s
.PHONY : src/auth/Auth.s

# target to generate assembly for a file
src/auth/Auth.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/infisical.dir/build.make CMakeFiles/infisical.dir/src/auth/Auth.cpp.s
.PHONY : src/auth/Auth.cpp.s

src/config/AuthenticationBuilder.o: src/config/AuthenticationBuilder.cpp.o
.PHONY : src/config/AuthenticationBuilder.o

# target to build an object file
src/config/AuthenticationBuilder.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/infisical.dir/build.make CMakeFiles/infisical.dir/src/config/AuthenticationBuilder.cpp.o
.PHONY : src/config/AuthenticationBuilder.cpp.o

src/config/AuthenticationBuilder.i: src/config/AuthenticationBuilder.cpp.i
.PHONY : src/config/AuthenticationBuilder.i

# target to preprocess a source file
src/config/AuthenticationBuilder.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/infisical.dir/build.make CMakeFiles/infisical.dir/src/config/AuthenticationBuilder.cpp.i
.PHONY : src/config/AuthenticationBuilder.cpp.i

src/config/AuthenticationBuilder.s: src/config/AuthenticationBuilder.cpp.s
.PHONY : src/config/AuthenticationBuilder.s

# target to generate assembly for a file
src/config/AuthenticationBuilder.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/infisical.dir/build.make CMakeFiles/infisical.dir/src/config/AuthenticationBuilder.cpp.s
.PHONY : src/config/AuthenticationBuilder.cpp.s

src/config/ConfigBuilder.o: src/config/ConfigBuilder.cpp.o
.PHONY : src/config/ConfigBuilder.o

# target to build an object file
src/config/ConfigBuilder.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/infisical.dir/build.make CMakeFiles/infisical.dir/src/config/ConfigBuilder.cpp.o
.PHONY : src/config/ConfigBuilder.cpp.o

src/config/ConfigBuilder.i: src/config/ConfigBuilder.cpp.i
.PHONY : src/config/ConfigBuilder.i

# target to preprocess a source file
src/config/ConfigBuilder.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/infisical.dir/build.make CMakeFiles/infisical.dir/src/config/ConfigBuilder.cpp.i
.PHONY : src/config/ConfigBuilder.cpp.i

src/config/ConfigBuilder.s: src/config/ConfigBuilder.cpp.s
.PHONY : src/config/ConfigBuilder.s

# target to generate assembly for a file
src/config/ConfigBuilder.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/infisical.dir/build.make CMakeFiles/infisical.dir/src/config/ConfigBuilder.cpp.s
.PHONY : src/config/ConfigBuilder.cpp.s

src/http/HttpClient.o: src/http/HttpClient.cpp.o
.PHONY : src/http/HttpClient.o

# target to build an object file
src/http/HttpClient.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/infisical.dir/build.make CMakeFiles/infisical.dir/src/http/HttpClient.cpp.o
.PHONY : src/http/HttpClient.cpp.o

src/http/HttpClient.i: src/http/HttpClient.cpp.i
.PHONY : src/http/HttpClient.i

# target to preprocess a source file
src/http/HttpClient.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/infisical.dir/build.make CMakeFiles/infisical.dir/src/http/HttpClient.cpp.i
.PHONY : src/http/HttpClient.cpp.i

src/http/HttpClient.s: src/http/HttpClient.cpp.s
.PHONY : src/http/HttpClient.s

# target to generate assembly for a file
src/http/HttpClient.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/infisical.dir/build.make CMakeFiles/infisical.dir/src/http/HttpClient.cpp.s
.PHONY : src/http/HttpClient.cpp.s

src/secrets/SecretsClient.o: src/secrets/SecretsClient.cpp.o
.PHONY : src/secrets/SecretsClient.o

# target to build an object file
src/secrets/SecretsClient.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/infisical.dir/build.make CMakeFiles/infisical.dir/src/secrets/SecretsClient.cpp.o
.PHONY : src/secrets/SecretsClient.cpp.o

src/secrets/SecretsClient.i: src/secrets/SecretsClient.cpp.i
.PHONY : src/secrets/SecretsClient.i

# target to preprocess a source file
src/secrets/SecretsClient.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/infisical.dir/build.make CMakeFiles/infisical.dir/src/secrets/SecretsClient.cpp.i
.PHONY : src/secrets/SecretsClient.cpp.i

src/secrets/SecretsClient.s: src/secrets/SecretsClient.cpp.s
.PHONY : src/secrets/SecretsClient.s

# target to generate assembly for a file
src/secrets/SecretsClient.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/infisical.dir/build.make CMakeFiles/infisical.dir/src/secrets/SecretsClient.cpp.s
.PHONY : src/secrets/SecretsClient.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... curl-generate-curl-config.1"
	@echo "... curl-generate-mk-ca-bundle.1"
	@echo "... curl-man"
	@echo "... curl-opts-man"
	@echo "... curl_uninstall"
	@echo "... cpr"
	@echo "... example"
	@echo "... infisical"
	@echo "... libcurl_shared"
	@echo "... zlib"
	@echo "... examples/example.o"
	@echo "... examples/example.i"
	@echo "... examples/example.s"
	@echo "... src/InfisicalClient.o"
	@echo "... src/InfisicalClient.i"
	@echo "... src/InfisicalClient.s"
	@echo "... src/auth/Auth.o"
	@echo "... src/auth/Auth.i"
	@echo "... src/auth/Auth.s"
	@echo "... src/config/AuthenticationBuilder.o"
	@echo "... src/config/AuthenticationBuilder.i"
	@echo "... src/config/AuthenticationBuilder.s"
	@echo "... src/config/ConfigBuilder.o"
	@echo "... src/config/ConfigBuilder.i"
	@echo "... src/config/ConfigBuilder.s"
	@echo "... src/http/HttpClient.o"
	@echo "... src/http/HttpClient.i"
	@echo "... src/http/HttpClient.s"
	@echo "... src/secrets/SecretsClient.o"
	@echo "... src/secrets/SecretsClient.i"
	@echo "... src/secrets/SecretsClient.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

